# Generated by Django 5.0.1 on 2024-01-31 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="time_end",
            field=models.DateTimeField(null=True),
        ),
    ]
